[package]
name = "chat-stream"
version = "0.1.0"
authors = ["Emmanuel Suarez Acevedo <emmanueljs1@gmail.com>"]

[dependencies]
relm = "^0.11.0"
relm-derive = "^0.11.0"
futures = "0.1"
pango = "0.3.0"
structopt = "0.2"

[dependencies.gtk]
version = "0.3.0"
features = ["v3_12"]
