[package]
name = "chat-server"
version = "0.1.0"
authors =  ["Emmanuel Suarez Acevedo <emmanueljs1@gmail.com>", "Yash Palkhiwala <15ypalkhiwala@gmail.com", "Megan Paik <megpaik@sas.upenn.edu>"]

[dependencies]
local-ip = "0.1"
structopt = "0.2"
